APP_FONT_FAMILY = "Segoe UI"

FONT_TITLE_XL = (APP_FONT_FAMILY, 22, "bold")
FONT_TITLE_LG = (APP_FONT_FAMILY, 18, "bold")
FONT_SUBTITLE = (APP_FONT_FAMILY, 10)
FONT_BODY = (APP_FONT_FAMILY, 10)
FONT_BODY_BOLD = (APP_FONT_FAMILY, 10, "bold")
FONT_LABEL_BOLD = (APP_FONT_FAMILY, 11, "bold")

SPACE_1 = 4
SPACE_2 = 8
SPACE_3 = 12
SPACE_4 = 16
SPACE_5 = 20

PANEL_PAD_X = 18
PANEL_PAD_Y = 14
CARD_PAD_X = 12
CARD_PAD_Y = 12
BUTTON_PAD_X = 6
BUTTON_PAD_Y = 4
